PRAGMA foreign_keys=ON;
CREATE TABLE local_surface_robustness_v1_runs (id INTEGER PRIMARY KEY,robustness_version TEXT NOT NULL,source_null_run_id INTEGER NOT NULL REFERENCES local_surface_null_v1_runs(id),config_hash TEXT NOT NULL,config_json TEXT NOT NULL,fitted_at TEXT NOT NULL,observation_count INTEGER NOT NULL CHECK(observation_count>0),distinct_session_dates INTEGER NOT NULL CHECK(distinct_session_dates>0),episode_count INTEGER NOT NULL CHECK(episode_count>0),repeated_episode_count INTEGER NOT NULL CHECK(repeated_episode_count>=0),readiness_state TEXT NOT NULL CHECK(readiness_state IN ('INSUFFICIENT_FOR_CROSS_DATE','CROSS_DATE_DESCRIPTIVE_ONLY','EXPLORATORY_STABILITY_ONLY','READY_FOR_PREREGISTRATION_REVIEW_ONLY')),p_values_enabled INTEGER NOT NULL DEFAULT 0 CHECK(p_values_enabled=0),fdr_enabled INTEGER NOT NULL DEFAULT 0 CHECK(fdr_enabled=0),decision_enabled INTEGER NOT NULL DEFAULT 0 CHECK(decision_enabled=0),UNIQUE(source_null_run_id,robustness_version,config_hash));
CREATE TABLE local_surface_robustness_v1_episodes (id INTEGER PRIMARY KEY,robustness_run_id INTEGER NOT NULL REFERENCES local_surface_robustness_v1_runs(id),episode_key TEXT NOT NULL,session_date TEXT NOT NULL,underlying TEXT NOT NULL,expiration TEXT NOT NULL,strike REAL NOT NULL,right TEXT NOT NULL CHECK(right IN('C','P')),observation_count INTEGER NOT NULL CHECK(observation_count>0),first_research_run_id INTEGER NOT NULL,last_research_run_id INTEGER NOT NULL,median_centered_residual REAL NOT NULL,peak_abs_centered_residual REAL NOT NULL CHECK(peak_abs_centered_residual>=0),max_spread_to_mid REAL,UNIQUE(robustness_run_id,episode_key));
CREATE TABLE local_surface_robustness_v1_daily_strata (id INTEGER PRIMARY KEY,robustness_run_id INTEGER NOT NULL REFERENCES local_surface_robustness_v1_runs(id),session_date TEXT NOT NULL,stratum_key TEXT NOT NULL,observation_count INTEGER NOT NULL CHECK(observation_count>0),median_centered_residual REAL NOT NULL,robust_scale REAL NOT NULL CHECK(robust_scale>=0),q025 REAL NOT NULL,q975 REAL NOT NULL,UNIQUE(robustness_run_id,session_date,stratum_key));
CREATE TABLE local_surface_robustness_v1_cross_date (id INTEGER PRIMARY KEY,robustness_run_id INTEGER NOT NULL REFERENCES local_surface_robustness_v1_runs(id),train_session_date TEXT NOT NULL,test_session_date TEXT NOT NULL,stratum_key TEXT NOT NULL,train_count INTEGER NOT NULL,test_count INTEGER NOT NULL,train_median REAL NOT NULL,train_robust_scale REAL NOT NULL,train_q025 REAL NOT NULL,train_q975 REAL NOT NULL,test_median REAL NOT NULL,test_robust_scale REAL NOT NULL,test_below_q025_count INTEGER NOT NULL,test_above_q975_count INTEGER NOT NULL,test_tail_fraction REAL NOT NULL CHECK(test_tail_fraction BETWEEN 0 AND 1),UNIQUE(robustness_run_id,train_session_date,test_session_date,stratum_key));
CREATE TABLE local_surface_robustness_v1_quality_sensitivity (id INTEGER PRIMARY KEY,robustness_run_id INTEGER NOT NULL REFERENCES local_surface_robustness_v1_runs(id),metric_name TEXT NOT NULL,bucket_name TEXT NOT NULL,observation_count INTEGER NOT NULL,median_abs_centered_residual REAL NOT NULL,q95_abs_centered_residual REAL NOT NULL,q99_abs_centered_residual REAL NOT NULL,UNIQUE(robustness_run_id,metric_name,bucket_name));
CREATE INDEX idx_robustness_episode_peak ON local_surface_robustness_v1_episodes(robustness_run_id,peak_abs_centered_residual DESC);
CREATE VIEW v_local_surface_robustness_v1_episode_summary AS SELECT r.id robustness_run_id,r.readiness_state,e.* FROM local_surface_robustness_v1_runs r JOIN local_surface_robustness_v1_episodes e ON e.robustness_run_id=r.id;
INSERT INTO schema_version(version,applied_at) SELECT 21,strftime('%Y-%m-%dT%H:%M:%SZ','now') WHERE NOT EXISTS(SELECT 1 FROM schema_version WHERE version=21);
